from typing import Protocol
from src.domain.entities.campo import Campo


class CampoRepositoryPort(Protocol):
    async def listar(self) -> list[Campo]: ...
    async def crear(self, c: Campo) -> Campo: ...
    async def eliminar(self, nombre_campo: str) -> bool: ...
