from typing import Protocol
from src.domain.entities.cultivo import Cultivo


class CultivoRepositoryPort(Protocol):
    async def listar(self) -> list[Cultivo]: ...
    async def crear(self, c: Cultivo) -> Cultivo: ...
    async def eliminar(self, nombre: str, variedad: str) -> bool: ...
