from typing import Protocol
from src.domain.entities.parcela import Parcela


class ParcelaRepositoryPort(Protocol):
    async def listar(self) -> list[Parcela]: ...
    async def crear(self, p: Parcela) -> Parcela: ...
    async def eliminar(self, nombre_parcela: str) -> bool: ...
